version: "3.8"

services:
  db-init:
    image: postgres:16
    volumes:
      - ./blockscout-db-data:/var/lib/postgresql/data
    entrypoint:
      - sh
      - -c
      - |
        chown -R 2000:2000 /var/lib/postgresql/data

  db:
    image: postgres:16
    restart: always
    container_name: "db"
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: "blockscout"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 7432:5432
    volumes:
      - ./blockscout-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blockscout -d blockscout"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
