version: "3.9"

services:
  redis_db:
    extends:
      file: ./services/docker-compose-redis.yml
      service: redis_db

  db-init:
    extends:
      file: ./services/docker-compose-db.yml
      service: db-init

  db:
    extends:
      file: ./services/docker-compose-db.yml
      service: db

  backend:
    depends_on:
      - db
      - redis_db
    extends:
      file: ./services/docker-compose-backend.yml
      service: backend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        API_V1_READ_METHODS_DISABLED: "false"
        DISABLE_WEBAPP: "false"
        API_V1_WRITE_METHODS_DISABLED: "false"
        CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        ADMIN_PANEL_ENABLED: ""
        RELEASE_VERSION: 5.3.3
    links:
      - db:database
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./envs/common-blockscout.env
    environment:
      ETHEREUM_JSONRPC_HTTP_URL: https://nova-0.gemini-3h.subspace.network/ws
      ETHEREUM_JSONRPC_TRACE_URL: https://nova-0.gemini-3h.subspace.network/ws
      ETHEREUM_JSONRPC_WS_URL: wss://nova-0.gemini-3h.subspace.network/ws
      DATABASE_URL: postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
      CHAIN_ID: "1002"
    volumes:
      - ./logs/:/app/logs/

  visualizer:
    extends:
      file: ./services/docker-compose-visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./services/docker-compose-sig-provider.yml
      service: sig-provider

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/docker-compose-frontend.yml
      service: frontend

  stats-db-init:
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats-db-init

  stats-db:
    depends_on:
      - backend
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats-db

  stats:
    depends_on:
      - stats-db
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats

  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/docker-compose-nginx.yml
      service: proxy

  agent:
    container_name: newrelic-infra
    image: newrelic/infrastructure:latest
    cap_add:
      - SYS_PTRACE
    network_mode: bridge
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      NRIA_LICENSE_KEY: "${NR_API_KEY}"
      NRIA_DISPLAY_NAME: "blockscout-gemini-3h"
    restart: unless-stopped
